package(default_visibility = ["//visibility:public"])

cc_library(
    name = "FaceMediaPipe",
    srcs = [
        "src/BgrToRgb.cpp",
        "src/LandmarkConversion.cpp",
        "src/FaceMediaPipe.cpp",
    ],
    hdrs = [
        "api/FaceMediaPipe.h",
        "src/BgrToRgb.h",
        "src/LandmarkConversion.h",
    ],
    includes = ["api"],
    deps = [
        "@mediapipe//mediapipe/framework/formats:image_frame",
        "@mediapipe//mediapipe/tasks/cc/vision/face_landmarker:face_landmarker",
    ],
    linkstatic = False,
)

cc_test(
    name = "bgr_to_rgb_test",
    srcs = [
        "src/BgrToRgb.cpp",
        "src/BgrToRgb.h",
        "../tests/bgr_to_rgb_test.cpp",
    ],
    includes = ["src"],
)

cc_test(
    name = "landmark_conversion_test",
    srcs = [
        "src/LandmarkConversion.cpp",
        "src/LandmarkConversion.h",
        "../tests/landmark_conversion_test.cpp",
    ],
    includes = [
        "api",
        "src",
    ],
)
