package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "FaceMediaPipe",
    srcs = ["src/FaceMediaPipe.cpp"],
    hdrs = ["api/FaceMediaPipe.h"],
    includes = ["api"],
    deps = [
        "@mediapipe//mediapipe/framework/formats:image_frame",
        "@mediapipe//mediapipe/tasks/cc/vision/face_landmarker:face_landmarker",
    ],
    linkshared = True,
    linkstatic = True,
)
